[project]
org-name = "ballerinai"
version = "@toml.version@"

[dependencies]
"ballerina/io" = "@stdlib.io.version@"
"ballerina/log" = "@stdlin.log.version@"
"ballerina/config"="@stdlib.config.version@"
"ballerina/http" = "@stdlib.http.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/cache" = "@stdlib.cache.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/task" = "@stdlib.task.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "transaction"
    version = "@project.version@"
    path = "../transaction-native/build/libs/transaction-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["transaction"]
