[package]
org = "ballerinai"
name = "transaction"
version = "0.0.0"

[[platform.java11.dependency]]
artifactId = "transaction"
version = "1.0.16"
path = "../transaction-native/build/libs/transaction-native-1.0.16.jar"
groupId = "ballerina"
