[package]
org = "ballerinai"
name = "transaction"
version = "1.0.16"

[[platform.java11.dependency]]
artifactId = "transaction"
version = "1.0.16-SNAPSHOT"
path = "../transaction-native/build/libss/transaction-native-1.0.16-SNAPSHOT.jar"
groupId = "ballerina"