[[dependency]]
org = "ballerina"
name = "io"
version = "0.5.5"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.0.5"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.0.5"

[[dependency]]
org = "ballerina"
name = "cache"
version = "2.0.5"

[[dependency]]
org = "ballerina"
name = "time"
version = "1.0.6"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "0.9.1"

[[dependency]]
org = "ballerina"
name = "task"
version = "1.1.5"
