[package]
org = "ballerinai"
name = "transaction_negative_tests"
version = "1.0.20"

[[platform.java11.dependency]]
path = "../transaction-native/build/libs/transaction-native-1.0.20-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "transaction"
version = "1.0.20-SNAPSHOT"

[[platform.java11.dependency]]
path = "../transaction-test-utils/build/libs/transaction-test-utils-1.0.20-SNAPSHOT.jar"
groupId = "org.ballerinalang.stdlib.transaction"
scope = "testOnly"
artifactId = "transaction"
version = "1.0.20-SNAPSHOT"

[[platform.java11.dependency]]
path = "./lib/io-native-1.2.1.jar"
groupId = "org.ballerinalang"
artifactId = "io-native"
version = "1.2.1"
