[package]
org = "ballerinai"
name = "transaction_negative_tests"
version = "1.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../transaction-native/build/libs/transaction-native-1.7.0-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "transaction"
version = "1.7.0-SNAPSHOT"

[[platform.java17.dependency]]
path = "../transaction-test-utils/build/libs/transaction-test-utils-1.7.0-SNAPSHOT.jar"
groupId = "org.ballerinalang.stdlib.transaction"
scope = "testOnly"
artifactId = "transaction"
version = "1.7.0-SNAPSHOT"

[[platform.java17.dependency]]
path = "./lib/io-native-1.5.0-20230622-110500-8523dfe.jar"
groupId = "org.ballerinalang"
artifactId = "io-native"
version = "1.5.0-20230622-110500-8523dfe"
